language: ruby
cache: bundler
sudo: enabled
before_install:
  - "./.travis/install_deps.sh"
  - gem update --system
  - gem install bundler
stages:
- name: test
- name: deploy
  if: tag IS present
jobs:
  include:
  - stage: test
    rvm: 2.5.1
    name: test osx
    script: "./.travis/test.sh"
    os: osx
  - stage: test
    name: test linux
    rvm: 2.5.1
    script: "./.travis/test.sh"
    os: linux
    dist: xenial
  - stage: deploy
    name: deploy osx
    rvm: 2.5.1
    os: osx
    script: "./.travis/deploy.sh"
  - stage: deploy
    name: deploy linux
    rvm: 2.5.1
    os: linux
    dist: xenial
    script: "./.travis/deploy.sh"
env:
  global:
  - secure: W+7Ex9Jg2qGsMSiVBDV4pppPrQI8NdWRZK8EEAdUF7vuM2gON9jHOTNHPbHe1SEuJJuaSAiT8cbpNMc5nZizpF3udVwYTYRcce9iMNwxhybze2T6ZBtJBEVhS1ToS3TeiDZdUKzesXGKjK82MDH3vBXIpRfvinyddRKwuqb/UTUnGyAChCKbwaHOsjpy7CoEz6ORk0rx4JQSDZogLQEwknIvpec81WVTIzVryFbicHx8bvg1jjBas8FzVq4eX0f+yocx7U5TaQoGD1eHQds6LNVdYzBNMGJSHQGlcsobm5XgEGihe6vGPhUblF8EekEQiI6b/CVXUT5d8FmrP9vbl3EI6sDlLp0Gb/M2iNK7Yd/vCdC+m0c8sHEikl20ZbjET4ajroTeXU72jQXmd8Ir1OrpLKADnv7JNHbjvQM2E+aHENTyUtWQnQFyU/P+DyVlwbM+6vz5GJxV8YheDsqjFDZx1jT6JctaYdaVN85+5Q/WgKPHTootYb93WN/7ft/dASk2Sz+wjdXfc8pG2AYmEdHOyJI+ilGJq3AcTdumWYOxI8o0EK0X+hEZGL4jk+5EGkI14J2UjJJN6k5K84Lf2AiJTuXMAiqNI5L1KLqSUsY+C91eCmiNk4rrh8kI/TmXPOX6D/7/jD0x3hFk87+uDC5yM1y34jIxs/skTe39NHw=
